# site properties and page defaults
title: Florin Lab
subtitle: "IKN-UKD"
description: "Website of Esther Florin's Neuroscience lab at the University Clinic of Düsseldorf (UKD)."
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: Esther.Florin@med.uni-duesseldorf.de
  orcid: 0000-0001-8276-2508
  google-scholar: 2iZ2Nl8AAAAJ
  github: FlorinNeuro
  twitter: florin_neuro
  # youtube: 

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
